<a href="https://colab.research.google.com/github/shrishti-04/DataAnalytics_Pandas_Numpy_Matplotlib_Seaborn/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np

# Let's define a one-dimensional array 
my_list = [5, 3, 8, 2]
my_list

[5, 3, 8, 2]

In [2]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([5, 3, 8, 2])

In [3]:
type(x)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
matrix = np.array(  [  [4, 9], [3, 7]  ]  )
matrix

array([[4, 9],
       [3, 7]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [5]:
my_matrix = np.array(  [  [4, 6, 8, 7], [20, 5, 6, 9]  ]  )
my_matrix

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.61700094, 0.0972703 , 0.70699813, 0.41789424, 0.1922849 ,
       0.66270506, 0.56553601, 0.66321217, 0.9871884 , 0.01195958,
       0.23274582, 0.74573584, 0.58191252, 0.62726083, 0.0300677 ])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(5, 5)
x

array([[0.92320195, 0.97926618, 0.32268668, 0.0093269 , 0.67010732],
       [0.98379446, 0.68313819, 0.70934569, 0.93264897, 0.02333849],
       [0.85456445, 0.93426965, 0.03929104, 0.74934714, 0.11129378],
       [0.06101065, 0.9851599 , 0.62865632, 0.60928328, 0.71771717],
       [0.84809115, 0.21168702, 0.58188591, 0.55545038, 0.04435083]])

In [8]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x

array([ 1.01058528, -0.54560801, -0.87360817,  0.3018954 ,  0.46930477,
        1.176179  , -0.08057882, -2.81016131, -0.73031179,  0.64097445])

In [9]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 10)
x

4

In [10]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 10, 6)
x

array([9, 8, 1, 3, 7, 4])

In [11]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 51)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
# Create an evenly spaced values with a step of 5
x = np.arange(1, 51, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [13]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [14]:
# Array of ones
x = np.ones(50)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# Matrices of ones
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [16]:
# Array of zeros
x = np.zeros((10, 10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [17]:
x = int(input('Enter your number: '))

i = np.random.randint(1, x, 20)
i

Enter your number: 30


array([29, 21,  3, 19,  3,  8, 22, 22,  8,  4, 15,  9, 25, 19,  7, 16, 23,
       23,  4, 24])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [18]:
# Let's define a one-dimensional array 
my_list = [13, -20, 4, 90, 20, 45, -30, 10]
my_list
x = np.array(my_list)
x

array([ 13, -20,   4,  90,  20,  45, -30,  10])

In [19]:
# Get Length of a numpy array
len(x)

8

In [20]:
# Get shape
x.shape

(8,)

In [21]:
# Obtain the datatype
x.dtype

dtype('int64')

In [22]:
# Reshape 1D array into a matrix
x = x.reshape(2, 4)
x

array([[ 13, -20,   4,  90],
       [ 20,  45, -30,  10]])

In [23]:
# Obtain the maximum element (value)
x.min()

-30

In [24]:
# Obtain the minimum element (value)
x.max()

90

In [25]:
# Obtain the location of the max element
x.argmax()

3

In [26]:
# Obtain the location of the min element
x.argmin()

6

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [27]:
x = np.arange(300, 500, 10)
x

array([300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
       430, 440, 450, 460, 470, 480, 490])

In [28]:
x = x.reshape(4, 5)
x

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

In [29]:
x.shape

(4, 5)

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [30]:
z = np.random.randint(-1000, 1000, (20, 20))
z

array([[-375, -260,  294,  198,  155,  482,   -5, -289,  762,  829, -892,
        -434,  589, -296,  102,  335,  564, -946, -573,  907],
       [-400, -146,   96,  374,   95, -561, -326, -615,  934,  591, -477,
         280,  173, -303, -577, -204,  591, -462,  619,  326],
       [ 867, -162, -905,  303, -966, -602,  737,  840, -574,  873,   69,
         605, -781,  525,  -47,  806, -711,  352, -458,  621],
       [ 546,  -80, -511, -720,  115,  334, -181,  529,  292, -214, -867,
        -599, -227,  550, -761,  136,   74,  744, -855, -848],
       [ 148,  -96, -284,   13, -655,  719, -539, -164, -960, -822, -446,
        -475, -574, -124,  474,  888,  745, -914, -965,  549],
       [-487, -436,  692,  279,  277,  540,  -56,  711,  903, -989, -642,
         -74,  795, -886,  756,  976,  681, -472,  982,  -16],
       [ 203, -316, -663,  -25,  -17,   53,  696, -760, -155,  643,  459,
         626,  495, -618, -413, -549,  803, -775, -928,  280],
       [-452, -519,  343, -112,  210, -46

In [31]:
z.shape

(20, 20)

In [32]:
z.min()

-997

In [33]:
z.max()

995

In [34]:
z.mean()

9.9325

In [35]:
print('Therefore the minimum value is {}, maximum value is {} and the average value is {}'.format(z.min(), z.max(), z.mean()))

Therefore the minimum value is -997, maximum value is 995 and the average value is 9.9325


# 4. MATHEMATICAL OPERATIONS

In [36]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
expo = np.exp(y)
expo

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [44]:
x = [3, 20, 30]
y = [4, 6, 7]

In [45]:
# the formula for distance is: sq(x^2 + y^2)
x = np.array([3, 20, 30])
y = np.array([4, 6, 7])

distance = list(np.sqrt(x**2 + y**2))
distance

[5.0, 20.8806130178211, 30.805843601498726]

# 5. SLICING AND INDEXING 

In [62]:
x = np.array([12, 28, 5, 21, 15, 6])
x

array([12, 28,  5, 21, 15,  6])

In [63]:
# Access specific index from the numpy array
x[2]

5

In [64]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[:3]

array([12, 28,  5])

In [65]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10,  5, 21, 15,  6])

In [66]:
# Let's define a two dimensional numpy array
x = np.random.randint(1, 10, (5, 5))
x

array([[2, 1, 6, 5, 3],
       [3, 8, 3, 4, 2],
       [6, 2, 3, 3, 3],
       [2, 9, 3, 7, 4],
       [5, 6, 9, 5, 6]])

In [67]:
# Get a row from a mtrix
x[0]

array([2, 1, 6, 5, 3])

In [68]:
# Get one element
x[2][3]

3

In [71]:
x[:3]

array([[2, 1, 6, 5, 3],
       [3, 8, 3, 4, 2],
       [6, 2, 3, 3, 3]])

In [72]:
mini_x = x[:, 2:]
mini_x

array([[6, 5, 3],
       [3, 4, 2],
       [3, 3, 3],
       [3, 7, 4],
       [9, 5, 6]])

In [74]:
mini_x = x[:, :2]
mini_x

array([[2, 1],
       [3, 8],
       [6, 2],
       [2, 9],
       [5, 6]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [83]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [84]:
x[-1] = -1
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [87]:
x[:2, 3:] = x[:2, 3:] * 2

In [88]:
x

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

# 6. ELEMENTS SELECTION (CONDITIONAL)

In [89]:
x = np.random.randint(1, 10, (5, 5))
x

array([[1, 3, 2, 4, 2],
       [1, 3, 6, 6, 4],
       [6, 7, 9, 2, 1],
       [3, 1, 1, 9, 1],
       [5, 1, 2, 1, 7]])

In [90]:
new_x = x[  x > 3  ]
new_x

array([4, 6, 6, 4, 6, 7, 9, 9, 5, 7])

In [91]:
new_x = x[  x%2 == 0  ]
new_x

array([2, 4, 2, 6, 6, 4, 6, 2, 2])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [92]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4, 40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [93]:
x[x < 0] = 0
x[x%2 == 1] = 25

In [94]:
x

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X